### PR TITLE
Fasta reader

### PR DESCRIPTION
**Pull request by RasmusFonseca**
Accidently worked on parser in this branch as well. Close after merging.

### CODE REVIEW

**Comment by AndreasDahl** [comment]
You should probably update the root readme, as it claims the project have no external dependencies under `Compiling Source`

**Comment by AndreasDahl** [comment]
It seems like travis is unable to at all build this pull request. It doesn't even get to the tests.

**Comment by AndreasDahl** [comment]
Will try to build, and will merge if it succeeds, when my other comments are resolved.

**Comment by RasmusFonseca** [comment]
Ok will look at it today. Trying to fix the tests directly in develop (we dont have the discipline that you do in klust =)

**Pull request merged**
